name: Pulumi-destroy
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*destroy*"
jobs:
  update:
    name: Destroy-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "stable"
      - run: go mod download
      - uses: pulumi/actions@v3
        with:
          command: destroy
          color: always
          stack-name: cloudnativerioja/cloudflare-iac-rioja/cloudflare-iac-rioja
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
